-- Standardized index names generated on 2026-01-13 22:08:55Z
-- Convention:
--   Non-unique: idx_<table>__<col1>__[<col2>...]
--   Unique:     ux_<table>__<col1>__[<col2>...]
--   Expression columns: expr_<hash>
--   Non-btree methods append: __gin/__gist/__hash/etc
--   Partial indexes append: __partial

-- Reordered on 2026-01-13 21:58:49Z
-- Tables first, indexes last (to make index failures easy to isolate).

-- network_tools schema bootstrap (PostgreSQL)
-- Source: init_nodes.sql (MariaDB/MySQL) converted to Postgres DDL
-- Notes:
--  - Intended to run inside the 'network_tools' database (set POSTGRES_DB=network_tools in the Postgres container).
--  - This script is idempotent (CREATE TABLE/INDEX IF NOT EXISTS).
--  - 'vault_account' and 'service_account' tables are intentionally omitted per request.
--  - MySQL user/grant/insert statements are intentionally omitted.
--
-- Recommended: place this file in /docker-entrypoint-initdb.d/ to run on first DB initialization,
-- or run manually with: psql -v ON_ERROR_STOP=1 -d network_tools -f <this_file>

BEGIN;

-- -----------------------------
-- TABLES
-- -----------------------------


CREATE TABLE IF NOT EXISTS app_backend_tracking (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  route varchar(255),
  datetimestamp timestamp,
  information text,
  CONSTRAINT app_backend_tracking__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS app_frontend_tracking (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  username varchar(255),
  route text,
  information text,
  datetimestamp timestamp,
  CONSTRAINT app_frontend_tracking__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS archived_device_provisioning_repository (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  device_host_name varchar(255),
  model_number varchar(255),
  expansion_module varchar(255),
  assigned_hub_id varchar(255),
  provisioning_status varchar(255),
  device_classification varchar(255),
  assigned_chassis_sn varchar(255),
  management_ip varchar(255),
  management_gateway varchar(255),
  information text,
  datetimestamp timestamp,
  CONSTRAINT archived_device_provisioning_repository__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS circuit_id (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  type varchar(255),
  information text,
  CONSTRAINT circuit_id__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS circuit_number_status (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  status varchar(255),
  information varchar(255),
  CONSTRAINT circuit_number_status__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS circuit_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  circuit_type varchar(255),
  information text,
  CONSTRAINT circuit_types__pk PRIMARY KEY (id),
  CONSTRAINT circuit_types__circuit_type_uniq__uq UNIQUE (circuit_type)
);


CREATE TABLE IF NOT EXISTS circuits (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  full_circuit_id varchar(255),
  circuit_id varchar(255),
  circuit_number varchar(255),
  terminating_station_cable varchar(255),
  terminating_station_pair varchar(255),
  status varchar(255),
  circuit_type varchar(255),
  originating_hub_id varchar(255),
  originating_hub_interface varchar(255),
  information text,
  requester varchar(255),
  new_request_id varchar(255),
  datetimestamp timestamp,
  CONSTRAINT circuits__pk PRIMARY KEY (id),
  CONSTRAINT circuits__circuit_number_uniq__uq UNIQUE (circuit_number),
  CONSTRAINT circuits__full_circuit_id_uniq__uq UNIQUE (full_circuit_id)
);

CREATE TABLE IF NOT EXISTS deleted_device_provisioning_repository (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  device_host_name varchar(255),
  model_number varchar(255),
  expansion_module varchar(255),
  assigned_hub_id varchar(255),
  provisioning_status varchar(255),
  device_classification varchar(255),
  assigned_chassis_sn varchar(255),
  management_ip varchar(255),
  management_gateway varchar(255),
  information text,
  datetimestamp timestamp,
  CONSTRAINT deleted_device_provisioning_repository__pk PRIMARY KEY (id),
  CONSTRAINT deleted_device_provisioning_repository__device_host_name__uq UNIQUE (device_host_name)
);

CREATE TABLE IF NOT EXISTS department_names (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  department_name varchar(255),
  information text,
  CONSTRAINT department_names__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS device_backup_locations (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  device_name varchar(255),
  ipv4_loopback varchar(15),
  ipv6_loopback varchar(255),
  device_type varchar(255),
  file_location varchar(255),
  datetimestamp timestamp,
  CONSTRAINT device_backup_locations__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS device_backup_que (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  device_name varchar(255),
  ipv4_loopback varchar(15),
  ipv6_loopback varchar(255),
  device_type varchar(255),
  datetimestamp timestamp,
  CONSTRAINT device_backup_que__pk PRIMARY KEY (id),
  CONSTRAINT device_backup_que__UQ_ipv4_loopback__uq UNIQUE (ipv4_loopback)
);

CREATE TABLE IF NOT EXISTS device_profile_development (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  model_number varchar(255),
  expansion_module boolean,
  compatible_with text,
  information text,
  datetimestamp timestamp,
  CONSTRAINT device_profile_development__pk PRIMARY KEY (id),
  CONSTRAINT device_profile_development__model__uq UNIQUE (model_number)
);


CREATE TABLE IF NOT EXISTS device_profile_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  model_number varchar(255),
  expansion_module boolean,
  compatible_with text,
  information text,
  datetimestamp timestamp,
  CONSTRAINT device_profile_history__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS device_profile_production (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  model_number varchar(255),
  expansion_module boolean,
  compatible_with text,
  information text,
  datetimestamp timestamp,
  CONSTRAINT device_profile_production__pk PRIMARY KEY (id),
  CONSTRAINT device_profile_production__model__uq UNIQUE (model_number)
);


CREATE TABLE IF NOT EXISTS device_reachability (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ipv4_address varchar(15),
  protocol varchar(255),
  datetimestamp timestamp,
  status integer,
  reachable_by text,
  profile_used varchar(255),
  CONSTRAINT device_reachability__pk PRIMARY KEY (id),
  CONSTRAINT device_reachability__ipv4_address__uq UNIQUE (ipv4_address)
);

CREATE TABLE IF NOT EXISTS device_reachability_unreachable (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ipv4_address varchar(15),
  protocol varchar(255),
  datetimestamp timestamp,
  status integer,
  unreachable_by text,
  CONSTRAINT device_reachability_unreachable__pk PRIMARY KEY (id),
  CONSTRAINT device_reachability_unreachable__ipv4_address__uq UNIQUE (ipv4_address)
);

CREATE TABLE IF NOT EXISTS devices (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  device_name varchar(255) NOT NULL DEFAULT '',
  hub_id varchar(255),
  site_abbreviation varchar(255),
  os varchar(255),
  version varchar(255),
  chassis_model varchar(255),
  ipv4_loopback varchar(15) NOT NULL DEFAULT '',
  ipv6_loopback varchar(255),
  device_type varchar(255) NOT NULL DEFAULT '',
  information text,
  information_detail text,
  datetimestamp timestamp,
  CONSTRAINT devices__pk PRIMARY KEY (id),
  CONSTRAINT devices__device_name__uq UNIQUE (device_name),
  CONSTRAINT devices__ipv4_loopback__uq UNIQUE (ipv4_loopback)
);

CREATE TABLE IF NOT EXISTS devices_archive (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  device_name varchar(255) NOT NULL DEFAULT '',
  hub_id varchar(255),
  site_abbreviation varchar(255),
  os varchar(255),
  version varchar(255),
  chassis_model varchar(255),
  ipv4_loopback varchar(15) NOT NULL DEFAULT '',
  ipv6_loopback varchar(255),
  device_type varchar(255) NOT NULL DEFAULT '',
  information text,
  information_detail text,
  datetimestamp timestamp,
  CONSTRAINT devices_archive__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS devices_no_profile (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  device_name varchar(255) NOT NULL DEFAULT '',
  os varchar(255),
  version varchar(255),
  chassis_model varchar(255),
  ipv4_loopback varchar(15) NOT NULL DEFAULT '',
  ipv6_loopback varchar(255),
  device_type varchar(255) NOT NULL DEFAULT '',
  information text,
  datetimestamp timestamp,
  CONSTRAINT devices_no_profile__pk PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS discovery_jobs_active (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ipv4_address varchar(255),
  datetimestamp timestamp,
  status boolean,
  CONSTRAINT discovery_jobs_active__pk PRIMARY KEY (id),
  CONSTRAINT discovery_jobs_active__ipv4_address__uq UNIQUE (ipv4_address)
);


CREATE TABLE IF NOT EXISTS discovery_jobs_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ipv4_address varchar(255),
  datetimestamp timestamp,
  CONSTRAINT discovery_jobs_history__pk PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS global_vlan_database (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  vlan_id integer,
  vlan_description varchar(31),
  information text,
  deployed_network varchar(255),
  CONSTRAINT global_vlan_database__pk PRIMARY KEY (id),
  CONSTRAINT global_vlan_database__vlan_id__uq UNIQUE (vlan_id)
);


CREATE TABLE IF NOT EXISTS hardware_inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  device_name varchar(255),
  chassis_model varchar(255),
  ipv4_loopback varchar(255),
  ipv6_loopback varchar(255),
  device_type varchar(255),
  serial_number varchar(255),
  model_name varchar(255),
  datetimestamp timestamp,
  CONSTRAINT hardware_inventory__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hardware_inventory_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  device_name varchar(255),
  chassis_model varchar(255),
  ipv4_loopback varchar(255),
  ipv6_loopback varchar(255),
  device_type varchar(255),
  serial_number varchar(255),
  model_name varchar(255),
  datetimestamp timestamp,
  CONSTRAINT hardware_inventory_history__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hardware_inventory_on_hand (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  location varchar(255),
  vendor varchar(255),
  type varchar(255),
  model_number varchar(255) NOT NULL,
  part_number varchar(255) NOT NULL,
  serial_number varchar(255) NOT NULL,
  install_date timestamp,
  purchase_date timestamp,
  purchase_order_number varchar(255),
  functional_area varchar(255),
  funding_source varchar(255),
  in_use_flag boolean,
  in_use_auto_discover_date timestamp,
  found_in_device_name varchar(255),
  rma_flag boolean,
  rma_date timestamp,
  rma_ship_to text,
  rma_tracking_number varchar(255),
  room_number varchar(255),
  assigned_subnet_number varchar(255),
  ethernet_address varchar(255),
  assigned_asset_tag varchar(255),
  spare_flag boolean,
  recycled_flag boolean,
  order_date timestamp,
  comments text,
  datetimestamp timestamp,
  last_updated_by varchar(255),
  CONSTRAINT hardware_inventory_on_hand__pk PRIMARY KEY (model_number, serial_number, part_number),
  CONSTRAINT hardware_inventory_on_hand__serial_number__uq UNIQUE (serial_number)
);

CREATE TABLE IF NOT EXISTS hardware_inventory_on_hand_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  location varchar(255),
  vendor varchar(255),
  type varchar(255),
  model_number varchar(255),
  part_number varchar(255),
  serial_number varchar(255),
  install_date timestamp,
  purchase_date timestamp,
  purchase_order_number varchar(255),
  functional_area varchar(255),
  funding_source varchar(255),
  in_use_flag boolean,
  in_use_auto_discover_date timestamp,
  found_in_device_name varchar(255),
  rma_flag boolean,
  rma_date timestamp,
  rma_ship_to text,
  rma_tracking_number varchar(255),
  room_number varchar(255),
  assigned_subnet_number varchar(255),
  ethernet_address varchar(255),
  assigned_asset_tag varchar(255),
  spare_flag boolean,
  recycled_flag boolean,
  order_date timestamp,
  comments text,
  datetimestamp timestamp,
  last_updated_by varchar(255),
  CONSTRAINT hardware_inventory_on_hand_history__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hub_id_list (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  hub_id varchar(255),
  device_name varchar(255),
  datetimestamp timestamp,
  CONSTRAINT hub_id_list__pk PRIMARY KEY (id),
  CONSTRAINT hub_id_list__hub_id__uq UNIQUE (hub_id),
  CONSTRAINT hub_id_list__device_name__uq UNIQUE (device_name)
);


CREATE TABLE IF NOT EXISTS hub_id_list_archive (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  hub_id varchar(255),
  device_name varchar(255),
  datetimestamp timestamp,
  CONSTRAINT hub_id_list_archive__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ipv4_exclude_from_discovery_scans (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  subnet varchar(255),
  added_by_user varchar(255),
  reason text,
  datetimestamp timestamp,
  CONSTRAINT ipv4_exclude_from_discovery_scans__pk PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS mac_address_table (
  ipv4_loopback varchar(15) NOT NULL,
  device_name varchar(255),
  chassis_model varchar(255),
  information text,
  ipv4_address varchar(15) NOT NULL DEFAULT '',
  age varchar(255),
  interface varchar(255) NOT NULL,
  interface_description varchar(255),
  mac_address varchar(255) NOT NULL,
  resolved_hostname varchar(255),
  base_ethernet_mac_address varchar(255),
  model_number varchar(255),
  system_serial_number varchar(255),
  datetimestamp timestamp,
  CONSTRAINT mac_address_table__cIndex_unique__uq UNIQUE (mac_address, interface, ipv4_address, ipv4_loopback)
);

CREATE TABLE IF NOT EXISTS new_device_provisioning_repository (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  device_host_name varchar(255),
  model_number varchar(255),
  expansion_module varchar(255),
  assigned_hub_id varchar(255),
  provisioning_status varchar(255),
  device_classification varchar(255),
  assigned_chassis_sn varchar(255),
  management_ip varchar(255),
  management_gateway varchar(255),
  information text,
  datetimestamp timestamp,
  CONSTRAINT new_device_provisioning_repository__pk PRIMARY KEY (id),
  CONSTRAINT new_device_provisioning_repository__device_host_name__uq UNIQUE (device_host_name)
);

CREATE TABLE IF NOT EXISTS production_device_provisioning_repository (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  device_host_name varchar(255),
  model_number varchar(255),
  expansion_module varchar(255),
  assigned_hub_id varchar(255),
  provisioning_status varchar(255),
  device_classification varchar(255),
  assigned_chassis_sn varchar(255),
  management_ip varchar(255),
  management_gateway varchar(255),
  information text,
  datetimestamp timestamp,
  CONSTRAINT production_device_provisioning_repository__pk PRIMARY KEY (id),
  CONSTRAINT production_device_provisioning_repository__device_host_name__uq UNIQUE (device_host_name)
);

CREATE TABLE IF NOT EXISTS reporting_cisco_api_cve_software (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  os varchar(255),
  version varchar(255),
  information text,
  datetimestamp timestamp,
  CONSTRAINT reporting_cisco_api_cve_software__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS reporting_cisco_api_eox (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  datetimestamp timestamp,
  information text,
  CONSTRAINT reporting_cisco_api_eox__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS site_location_information (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  location_name varchar(255),
  site_abbreviation varchar(255),
  street_address varchar(255),
  city varchar(255),
  state varchar(255),
  postal_code varchar(255),
  country varchar(255),
  latitude varchar(255),
  longitude varchar(255),
  information text,
  datetimestamp timestamp,
  CONSTRAINT site_location_information__pk PRIMARY KEY (id),
  CONSTRAINT site_location_information__site_id__uq UNIQUE (site_abbreviation)
);

CREATE TABLE IF NOT EXISTS templates_active (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  template_name varchar(255),
  attached_to_device varchar(255),
  template_version varchar(255),
  template_variables text,
  function varchar(255),
  information text,
  locked_for_editing varchar(255),
  approved_for_production varchar(255),
  last_edited_by varchar(255),
  datetimestamp timestamp,
  CONSTRAINT templates_active__pk PRIMARY KEY (id),
  CONSTRAINT templates_active__template_name__uq UNIQUE (template_name)
);

CREATE TABLE IF NOT EXISTS templates_deleted (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  template_name varchar(255),
  attached_to_device varchar(255),
  template_version varchar(255),
  template_variables text,
  function varchar(255),
  information text,
  locked_for_editing varchar(255),
  approved_for_production varchar(255),
  last_edited_by varchar(255),
  datetimestamp timestamp,
  CONSTRAINT templates_deleted__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS templates_development (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  template_name varchar(255),
  attached_to_device varchar(255),
  template_version varchar(255),
  template_variables text,
  function varchar(255),
  information text,
  locked_for_editing varchar(255),
  approved_for_production varchar(255),
  last_edited_by varchar(255),
  datetimestamp timestamp,
  CONSTRAINT templates_development__pk PRIMARY KEY (id),
  CONSTRAINT templates_development__template_name__uq UNIQUE (template_name)
);

CREATE TABLE IF NOT EXISTS templates_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  template_name varchar(255),
  attached_to_device varchar(255),
  template_version varchar(255),
  function varchar(255),
  template_variables text,
  information text,
  locked_for_editing varchar(255),
  approved_for_production varchar(255),
  last_edited_by varchar(255),
  datetimestamp timestamp,
  CONSTRAINT templates_history__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "UserTable" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email varchar(255),
  roles text,
  sub varchar(255),
  azp varchar(255),
  name varchar(255),
  preferred_username varchar(255),
  given_name varchar(255),
  family_name varchar(255),
  md5 varchar(255),
  enabled boolean,
  last_login timestamp,
  assigned_department varchar(255),
  CONSTRAINT UserTable__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS vault_information (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  path varchar(255),
  key_name varchar(255),
  information text,
  datetimestamp timestamp,
  md5 varchar(255),
  CONSTRAINT vault_information__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS vault_information_archive (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  path varchar(255),
  key_name varchar(255),
  information text,
  datetimestamp timestamp,
  md5 varchar(255),
  CONSTRAINT vault_information_archive__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS software_transfer_status (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ipv4_loopback varchar(15),
  information jsonb NOT NULL,
  serial_number varchar(255) GENERATED ALWAYS AS ((information->>'serial_number')) STORED,
  model_number varchar(255) GENERATED ALWAYS AS ((information->>'model_number')) STORED,
  file_name varchar(255) GENERATED ALWAYS AS ((information->>'filename')) STORED,
  status varchar(255),
  datetimestamp timestamp,
  info_progress varchar(255) GENERATED ALWAYS AS ((information->>'progress')) STORED,
  CONSTRAINT software_transfer_status__pk PRIMARY KEY (id),
  CONSTRAINT software_transfer_status__uq_status_loopback_filename__uq UNIQUE (ipv4_loopback, file_name, serial_number, model_number)
);

CREATE TABLE IF NOT EXISTS software_transfer_status_que (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ipv4_loopback varchar(15),
  information jsonb NOT NULL,
  serial_number varchar(255) GENERATED ALWAYS AS ((information->>'serial_number')) STORED,
  model_number varchar(255) GENERATED ALWAYS AS ((information->>'model_number')) STORED,
  file_name varchar(255) GENERATED ALWAYS AS ((information->>'filename')) STORED,
  status varchar(255),
  datetimestamp timestamp,
  info_progress varchar(255) GENERATED ALWAYS AS ((information->>'progress')) STORED,
  CONSTRAINT software_transfer_status_que__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS software_transfer_status_que_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ipv4_loopback varchar(15),
  file_name varchar(255),
  information text,
  status varchar(255),
  datetimestamp timestamp,
  CONSTRAINT software_transfer_status_que_history__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS switch_power_consumption (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ipv4_loopback varchar(14),
  device_name varchar(255),
  chassis_model varchar(255),
  information text,
  datetimestamp timestamp,
  CONSTRAINT switch_power_consumption__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS device_mac_table_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ipv4_loopback varchar(15),
  device_name varchar(255),
  information text,
  information_type varchar(255),
  datetimestamp timestamp,
  CONSTRAINT device_mac_table_data__pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS access_list_statistics_table (
  ipv4_loopback varchar(15),
  device_name varchar(255),
  chassis_model varchar(255),
  information text,
  access_list_group varchar(255),
  access_list_line integer,
  access_list_rule varchar(255),
  access_list_matches bigint,
  datetimestamp timestamp
);

CREATE TABLE IF NOT EXISTS ip_arp_table (
  ipv4_loopback varchar(15) NOT NULL,
  device_name varchar(255),
  chassis_model varchar(255),
  information text,
  ipv4_address varchar(15) NOT NULL DEFAULT '',
  age varchar(255),
  interface varchar(255) NOT NULL,
  interface_description varchar(255),
  mac_address varchar(255) NOT NULL,
  resolved_hostname varchar(255),
  base_ethernet_mac_address varchar(255),
  model_number varchar(255),
  system_serial_number varchar(255),
  datetimestamp timestamp,
  CONSTRAINT ip_arp_table__pk PRIMARY KEY (ipv4_address, interface, ipv4_loopback)
);

CREATE TABLE IF NOT EXISTS wiring_database (
  circuit_id varchar(255) NOT NULL DEFAULT '',
  circuit_id_number integer NOT NULL,
  circuit_id_status varchar(255),
  circuit_id_full varchar(255) NOT NULL,
  subnet varchar(255),
  anomoly varchar(255),
  hub varchar(255),
  hub_name varchar(255),
  hub_ip varchar(15),
  port varchar(255),
  port_type varchar(255),
  department varchar(255),
  originating_building varchar(255),
  originating_room varchar(255),
  trunk_cable varchar(255),
  trunk_pair varchar(255),
  terminating_building varchar(255),
  terminating_room varchar(255),
  station_cable varchar(255),
  station_pair varchar(255),
  install_order_number varchar(255),
  change_order varchar(255),
  technician varchar(255),
  install_date timestamp,
  information text,
  comments text,
  datetimestamp timestamp,
  requester varchar(255),
  requester_datetime timestamp,
  res_hall_service_number varchar(255),
  res_hall_building varchar(255),
  res_hall_cable_identifier varchar(255),
  res_hall_remote_location varchar(255),
  res_hall_nynex_cable_number varchar(255),
  res_hall_cable_id varchar(255),
  res_hall_cable_description varchar(255),
  res_hall_purpose varchar(255),
  res_hall_originating_location varchar(255),
  res_hall_room_location varchar(255),
  res_hall_room_location_code varchar(255),
  res_hall_faceplate_position varchar(255),
  res_hall_originating_tr varchar(255),
  res_hall_vlan integer,
  res_hall_tr_room_number varchar(255),
  res_hall_function varchar(255),
  last_updated_by_user varchar(255),
  CONSTRAINT wiring_database__pk PRIMARY KEY (circuit_id, circuit_id_number, circuit_id_full)
);

CREATE TABLE IF NOT EXISTS circuit_install_technicians (
  install_technician varchar(255) NOT NULL DEFAULT '',
  CONSTRAINT circuit_install_technicians__pk PRIMARY KEY (install_technician)
);


CREATE TABLE IF NOT EXISTS access_list_statistics_table_processed (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  data_type varchar(255),
  data_information text,
  in_process boolean,
  datetimestamp timestamp,
  CONSTRAINT access_list_statistics_table_processed__pk PRIMARY KEY (id),
  CONSTRAINT access_list_statistics_table_processed__data_type__uq UNIQUE (data_type)
);


CREATE TABLE IF NOT EXISTS discovered_device_configuration_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  information jsonb NOT NULL,
  ipv4_loopback varchar(45) GENERATED ALWAYS AS ((information->>'ipv4_loopback')) STORED,
  device_type varchar(255) GENERATED ALWAYS AS ((information->>'device_type')) STORED,
  hostname varchar(255) GENERATED ALWAYS AS ((information->>'hostname')) STORED,
  system_serial_number varchar(64) GENERATED ALWAYS AS ((information->>'system_serial_number')) STORED,
  model_number varchar(64) GENERATED ALWAYS AS ((information->>'model_number')) STORED,
  version varchar(64) GENERATED ALWAYS AS ((information->>'version')) STORED,
  datetimestamp timestamp,
  CONSTRAINT discovered_device_configuration_profiles__pk PRIMARY KEY (id)
);

-- -----------------------------
-- INDEXES
-- -----------------------------

CREATE INDEX IF NOT EXISTS idx_app_backend_tracking__datetimestamp ON app_backend_tracking (datetimestamp);
CREATE INDEX IF NOT EXISTS idx_app_backend_tracking__route ON app_backend_tracking (route);
CREATE INDEX IF NOT EXISTS idx_app_frontend_tracking__username ON app_frontend_tracking (username);
CREATE INDEX IF NOT EXISTS idx_app_frontend_tracking__route ON app_frontend_tracking (route);
CREATE INDEX IF NOT EXISTS idx_app_frontend_tracking__datetimestamp ON app_frontend_tracking (datetimestamp);
CREATE INDEX IF NOT EXISTS idx_archived_device_provisioning_repository__device_host_name ON archived_device_provisioning_repository (device_host_name);
CREATE INDEX IF NOT EXISTS idx_archived_device_provisioning_repository__assigned_hub_id ON archived_device_provisioning_repository (assigned_hub_id);
CREATE INDEX IF NOT EXISTS idx_archived_device_provisioning_repository__device_cl_e77e97bc ON archived_device_provisioning_repository (device_classification);
CREATE INDEX IF NOT EXISTS idx_archived_device_provisioning_repository__management_ip ON archived_device_provisioning_repository (management_ip);
CREATE INDEX IF NOT EXISTS idx_archived_device_provisioning_repository__management_gateway ON archived_device_provisioning_repository (management_gateway);
CREATE INDEX IF NOT EXISTS idx_archived_device_provisioning_repository__datetimestamp ON archived_device_provisioning_repository (datetimestamp);
CREATE INDEX IF NOT EXISTS idx_circuit_id__type ON circuit_id (type);
CREATE INDEX IF NOT EXISTS idx_circuit_number_status__status ON circuit_number_status (status);
CREATE INDEX IF NOT EXISTS idx_circuits__circuit_id ON circuits (circuit_id);
CREATE INDEX IF NOT EXISTS idx_circuits__status ON circuits (status);
CREATE INDEX IF NOT EXISTS idx_circuits__circuit_type ON circuits (circuit_type);
CREATE INDEX IF NOT EXISTS idx_circuits__originating_hub_id ON circuits (originating_hub_id);
CREATE INDEX IF NOT EXISTS idx_circuits__originating_hub_interface ON circuits (originating_hub_interface);
CREATE INDEX IF NOT EXISTS idx_circuits__terminating_station_cable ON circuits (terminating_station_cable);
CREATE INDEX IF NOT EXISTS idx_circuits__terminating_station_pair ON circuits (terminating_station_pair);
CREATE INDEX IF NOT EXISTS idx_circuits__requester ON circuits (requester);
CREATE INDEX IF NOT EXISTS idx_circuits__new_request_id ON circuits (new_request_id);
CREATE INDEX IF NOT EXISTS idx_deleted_device_provisioning_repository__assigned_hub_id ON deleted_device_provisioning_repository (assigned_hub_id);
CREATE INDEX IF NOT EXISTS idx_deleted_device_provisioning_repository__device_cla_fea81ee5 ON deleted_device_provisioning_repository (device_classification);
CREATE INDEX IF NOT EXISTS idx_deleted_device_provisioning_repository__management_ip ON deleted_device_provisioning_repository (management_ip);
CREATE INDEX IF NOT EXISTS idx_deleted_device_provisioning_repository__management_gateway ON deleted_device_provisioning_repository (management_gateway);
CREATE INDEX IF NOT EXISTS idx_deleted_device_provisioning_repository__datetimestamp ON deleted_device_provisioning_repository (datetimestamp);
CREATE INDEX IF NOT EXISTS idx_department_names__department_name ON department_names (department_name);
CREATE INDEX IF NOT EXISTS idx_device_backup_locations__device_name ON device_backup_locations (device_name);
CREATE INDEX IF NOT EXISTS idx_device_backup_locations__ipv4_loopback ON device_backup_locations (ipv4_loopback);
CREATE INDEX IF NOT EXISTS idx_device_backup_locations__ipv6_loopback ON device_backup_locations (ipv6_loopback);
CREATE INDEX IF NOT EXISTS idx_device_backup_locations__device_type ON device_backup_locations (device_type);
CREATE INDEX IF NOT EXISTS idx_device_backup_locations__datetimestamp ON device_backup_locations (datetimestamp);
CREATE INDEX IF NOT EXISTS idx_device_backup_que__device_name ON device_backup_que (device_name);
CREATE INDEX IF NOT EXISTS idx_device_backup_que__ipv6_loopback ON device_backup_que (ipv6_loopback);
CREATE INDEX IF NOT EXISTS idx_device_backup_que__device_type ON device_backup_que (device_type);
CREATE INDEX IF NOT EXISTS idx_device_profile_history__model_number ON device_profile_history (model_number);
CREATE INDEX IF NOT EXISTS idx_device_reachability__protocol ON device_reachability (protocol);
CREATE INDEX IF NOT EXISTS idx_device_reachability__status ON device_reachability (status);
CREATE INDEX IF NOT EXISTS idx_device_reachability_unreachable__protocol ON device_reachability_unreachable (protocol);
CREATE INDEX IF NOT EXISTS idx_device_reachability_unreachable__status ON device_reachability_unreachable (status);
CREATE INDEX IF NOT EXISTS idx_devices__ipv6_loopback ON devices (ipv6_loopback);
CREATE INDEX IF NOT EXISTS idx_devices__device_type ON devices (device_type);
CREATE INDEX IF NOT EXISTS idx_devices__chassis_model ON devices (chassis_model);
CREATE INDEX IF NOT EXISTS idx_devices__os ON devices (os);
CREATE INDEX IF NOT EXISTS idx_devices__version ON devices (version);
CREATE INDEX IF NOT EXISTS idx_devices__site_abbreviation ON devices (site_abbreviation);
CREATE INDEX IF NOT EXISTS idx_devices__hub_id ON devices (hub_id);
CREATE INDEX IF NOT EXISTS idx_devices_archive__device_name ON devices_archive (device_name);
CREATE INDEX IF NOT EXISTS idx_devices_archive__ipv4_loopback ON devices_archive (ipv4_loopback);
CREATE INDEX IF NOT EXISTS idx_devices_archive__ipv6_loopback ON devices_archive (ipv6_loopback);
CREATE INDEX IF NOT EXISTS idx_devices_archive__device_type ON devices_archive (device_type);
CREATE INDEX IF NOT EXISTS idx_devices_archive__chassis_model ON devices_archive (chassis_model);
CREATE INDEX IF NOT EXISTS idx_devices_archive__os ON devices_archive (os);
CREATE INDEX IF NOT EXISTS idx_devices_archive__version ON devices_archive (version);
CREATE INDEX IF NOT EXISTS idx_devices_no_profile__device_name ON devices_no_profile (device_name);
CREATE INDEX IF NOT EXISTS idx_devices_no_profile__ipv4_loopback ON devices_no_profile (ipv4_loopback);
CREATE INDEX IF NOT EXISTS idx_devices_no_profile__ipv6_loopback ON devices_no_profile (ipv6_loopback);
CREATE INDEX IF NOT EXISTS idx_devices_no_profile__device_type ON devices_no_profile (device_type);
CREATE INDEX IF NOT EXISTS idx_devices_no_profile__chassis_model ON devices_no_profile (chassis_model);
CREATE INDEX IF NOT EXISTS idx_devices_no_profile__os ON devices_no_profile (os);
CREATE INDEX IF NOT EXISTS idx_devices_no_profile__version ON devices_no_profile (version);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory__device_name ON hardware_inventory (device_name);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory__chassis_model ON hardware_inventory (chassis_model);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory__ipv4_loopback ON hardware_inventory (ipv4_loopback);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory__ipv6_loopback ON hardware_inventory (ipv6_loopback);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory__device_type ON hardware_inventory (device_type);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory__serial_number ON hardware_inventory (serial_number);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory__model_name ON hardware_inventory (model_name);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_history__device_name ON hardware_inventory_history (device_name);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_history__chassis_model ON hardware_inventory_history (chassis_model);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_history__ipv4_loopback ON hardware_inventory_history (ipv4_loopback);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_history__ipv6_loopback ON hardware_inventory_history (ipv6_loopback);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_history__device_type ON hardware_inventory_history (device_type);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_history__serial_number ON hardware_inventory_history (serial_number);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_history__model_name ON hardware_inventory_history (model_name);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__id ON hardware_inventory_on_hand (id);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__location ON hardware_inventory_on_hand (location);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__vendor ON hardware_inventory_on_hand (vendor);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__type ON hardware_inventory_on_hand (type);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__purchase_date ON hardware_inventory_on_hand (purchase_date);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__purchase_order_number ON hardware_inventory_on_hand (purchase_order_number);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__funding_source ON hardware_inventory_on_hand (funding_source);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__in_use_flag ON hardware_inventory_on_hand (in_use_flag);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__in_use_auto_discover_date ON hardware_inventory_on_hand (in_use_auto_discover_date);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__found_in_device_name ON hardware_inventory_on_hand (found_in_device_name);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__rma_flag ON hardware_inventory_on_hand (rma_flag);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__rma_date ON hardware_inventory_on_hand (rma_date);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__rma_ship_to ON hardware_inventory_on_hand (rma_ship_to);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__rma_tracking_number ON hardware_inventory_on_hand (rma_tracking_number);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__spare_flag ON hardware_inventory_on_hand (spare_flag);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__recycled_flag ON hardware_inventory_on_hand (recycled_flag);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__order_date ON hardware_inventory_on_hand (order_date);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__datetimestamp ON hardware_inventory_on_hand (datetimestamp);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__functional_area ON hardware_inventory_on_hand (functional_area);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__room_number ON hardware_inventory_on_hand (room_number);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__ethernet_address ON hardware_inventory_on_hand (ethernet_address);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand__assigned_subnet_number ON hardware_inventory_on_hand (assigned_subnet_number);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__location ON hardware_inventory_on_hand_history (location);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__vendor ON hardware_inventory_on_hand_history (vendor);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__type ON hardware_inventory_on_hand_history (type);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__model_number ON hardware_inventory_on_hand_history (model_number);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__part_number ON hardware_inventory_on_hand_history (part_number);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__serial_number ON hardware_inventory_on_hand_history (serial_number);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__purchase_date ON hardware_inventory_on_hand_history (purchase_date);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__purchase_order_number ON hardware_inventory_on_hand_history (purchase_order_number);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__funding_source ON hardware_inventory_on_hand_history (funding_source);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__in_use_flag ON hardware_inventory_on_hand_history (in_use_flag);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__in_use_auto_di_3468332e ON hardware_inventory_on_hand_history (in_use_auto_discover_date);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__found_in_device_name ON hardware_inventory_on_hand_history (found_in_device_name);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__rma_flag ON hardware_inventory_on_hand_history (rma_flag);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__rma_date ON hardware_inventory_on_hand_history (rma_date);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__rma_ship_to ON hardware_inventory_on_hand_history (rma_ship_to);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__rma_tracking_number ON hardware_inventory_on_hand_history (rma_tracking_number);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__spare_flag ON hardware_inventory_on_hand_history (spare_flag);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__recycled_flag ON hardware_inventory_on_hand_history (recycled_flag);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__order_date ON hardware_inventory_on_hand_history (order_date);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__datetimestamp ON hardware_inventory_on_hand_history (datetimestamp);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__functional_area ON hardware_inventory_on_hand_history (functional_area);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__room_number ON hardware_inventory_on_hand_history (room_number);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__ethernet_address ON hardware_inventory_on_hand_history (ethernet_address);
CREATE INDEX IF NOT EXISTS idx_hardware_inventory_on_hand_history__assigned_subnet_number ON hardware_inventory_on_hand_history (assigned_subnet_number);
CREATE INDEX IF NOT EXISTS idx_hub_id_list_archive__hub_id ON hub_id_list_archive (hub_id);
CREATE INDEX IF NOT EXISTS idx_hub_id_list_archive__device_name ON hub_id_list_archive (device_name);
CREATE INDEX IF NOT EXISTS idx_mac_address_table__interface_description ON mac_address_table (interface_description);
CREATE INDEX IF NOT EXISTS idx_new_device_provisioning_repository__assigned_hub_id ON new_device_provisioning_repository (assigned_hub_id);
CREATE INDEX IF NOT EXISTS idx_new_device_provisioning_repository__device_classification ON new_device_provisioning_repository (device_classification);
CREATE INDEX IF NOT EXISTS idx_new_device_provisioning_repository__management_ip ON new_device_provisioning_repository (management_ip);
CREATE INDEX IF NOT EXISTS idx_new_device_provisioning_repository__management_gateway ON new_device_provisioning_repository (management_gateway);
CREATE INDEX IF NOT EXISTS idx_new_device_provisioning_repository__datetimestamp ON new_device_provisioning_repository (datetimestamp);
CREATE INDEX IF NOT EXISTS idx_production_device_provisioning_repository__assigned_hub_id ON production_device_provisioning_repository (assigned_hub_id);
CREATE INDEX IF NOT EXISTS idx_production_device_provisioning_repository__device_65c3cb09 ON production_device_provisioning_repository (device_classification);
CREATE INDEX IF NOT EXISTS idx_production_device_provisioning_repository__management_ip ON production_device_provisioning_repository (management_ip);
CREATE INDEX IF NOT EXISTS idx_production_device_provisioning_repository__managem_f6b4c6a6 ON production_device_provisioning_repository (management_gateway);
CREATE INDEX IF NOT EXISTS idx_production_device_provisioning_repository__datetimestamp ON production_device_provisioning_repository (datetimestamp);
CREATE INDEX IF NOT EXISTS idx_reporting_cisco_api_cve_software__datetimestamp ON reporting_cisco_api_cve_software (datetimestamp);
CREATE INDEX IF NOT EXISTS idx_reporting_cisco_api_eox__datetimestamp ON reporting_cisco_api_eox (datetimestamp);
CREATE INDEX IF NOT EXISTS idx_site_location_information__location_name ON site_location_information (location_name);
CREATE INDEX IF NOT EXISTS idx_site_location_information__street_address ON site_location_information (street_address);
CREATE INDEX IF NOT EXISTS idx_site_location_information__city ON site_location_information (city);
CREATE INDEX IF NOT EXISTS idx_site_location_information__postal_code ON site_location_information (postal_code);
CREATE INDEX IF NOT EXISTS idx_site_location_information__country ON site_location_information (country);
CREATE INDEX IF NOT EXISTS idx_site_location_information__datetimestamp ON site_location_information (datetimestamp);
CREATE INDEX IF NOT EXISTS idx_templates_active__attached_to_device ON templates_active (attached_to_device);
CREATE INDEX IF NOT EXISTS idx_templates_active__function ON templates_active (function);
CREATE INDEX IF NOT EXISTS idx_templates_deleted__template_name ON templates_deleted (template_name);
CREATE INDEX IF NOT EXISTS idx_templates_deleted__attached_to_device ON templates_deleted (attached_to_device);
CREATE INDEX IF NOT EXISTS idx_templates_deleted__function ON templates_deleted (function);
CREATE INDEX IF NOT EXISTS idx_templates_development__attached_to_device ON templates_development (attached_to_device);
CREATE INDEX IF NOT EXISTS idx_templates_development__function ON templates_development (function);
CREATE INDEX IF NOT EXISTS idx_templates_history__template_name ON templates_history (template_name);
CREATE INDEX IF NOT EXISTS idx_templates_history__attached_to_device ON templates_history (attached_to_device);
CREATE INDEX IF NOT EXISTS idx_templates_history__function ON templates_history (function);
CREATE INDEX IF NOT EXISTS idx_usertable__email ON "UserTable" (email);
CREATE INDEX IF NOT EXISTS idx_usertable__preferred_username ON "UserTable" (preferred_username);
CREATE INDEX IF NOT EXISTS idx_usertable__given_name ON "UserTable" (given_name);
CREATE INDEX IF NOT EXISTS idx_usertable__family_name ON "UserTable" (family_name);
CREATE INDEX IF NOT EXISTS idx_usertable__enabled ON "UserTable" (enabled);
CREATE INDEX IF NOT EXISTS idx_usertable__last_login ON "UserTable" (last_login);
CREATE INDEX IF NOT EXISTS idx_vault_information__path ON vault_information (path);
CREATE INDEX IF NOT EXISTS idx_vault_information__key_name ON vault_information (key_name);
CREATE INDEX IF NOT EXISTS idx_vault_information_archive__path ON vault_information_archive (path);
CREATE INDEX IF NOT EXISTS idx_vault_information_archive__key_name ON vault_information_archive (key_name);
CREATE INDEX IF NOT EXISTS idx_software_transfer_status__ipv4_loopback ON software_transfer_status (ipv4_loopback);
CREATE INDEX IF NOT EXISTS idx_software_transfer_status__status ON software_transfer_status (status);
CREATE INDEX IF NOT EXISTS idx_software_transfer_status__file_name ON software_transfer_status (file_name);
CREATE INDEX IF NOT EXISTS idx_software_transfer_status__model_number ON software_transfer_status (model_number);
CREATE INDEX IF NOT EXISTS idx_software_transfer_status__info_progress ON software_transfer_status (info_progress);
CREATE INDEX IF NOT EXISTS idx_software_transfer_status_que__ipv4_loopback ON software_transfer_status_que (ipv4_loopback);
CREATE INDEX IF NOT EXISTS idx_software_transfer_status_que__status ON software_transfer_status_que (status);
CREATE INDEX IF NOT EXISTS idx_software_transfer_status_que__model_number ON software_transfer_status_que (model_number);
CREATE INDEX IF NOT EXISTS idx_software_transfer_status_que__info_progress ON software_transfer_status_que (info_progress);
CREATE INDEX IF NOT EXISTS idx_software_transfer_status_que__file_name ON software_transfer_status_que (file_name);
CREATE INDEX IF NOT EXISTS idx_software_transfer_status_que_history__ipv4_loopback ON software_transfer_status_que_history (ipv4_loopback);
CREATE INDEX IF NOT EXISTS idx_software_transfer_status_que_history__status ON software_transfer_status_que_history (status);
CREATE INDEX IF NOT EXISTS idx_software_transfer_status_que_history__file_name ON software_transfer_status_que_history (file_name);
CREATE INDEX IF NOT EXISTS idx_switch_power_consumption__ipv4_loopback ON switch_power_consumption (ipv4_loopback);
CREATE INDEX IF NOT EXISTS idx_switch_power_consumption__device_name ON switch_power_consumption (device_name);
CREATE INDEX IF NOT EXISTS idx_switch_power_consumption__chassis_model ON switch_power_consumption (chassis_model);
CREATE INDEX IF NOT EXISTS idx_switch_power_consumption__datetimestamp ON switch_power_consumption (datetimestamp);
CREATE INDEX IF NOT EXISTS idx_device_mac_table_data__ipv4_loopback ON device_mac_table_data (ipv4_loopback);
CREATE INDEX IF NOT EXISTS idx_device_mac_table_data__device_name ON device_mac_table_data (device_name);
CREATE INDEX IF NOT EXISTS idx_device_mac_table_data__information_type ON device_mac_table_data (information_type);
CREATE INDEX IF NOT EXISTS idx_device_mac_table_data__datetimestamp ON device_mac_table_data (datetimestamp);
CREATE INDEX IF NOT EXISTS idx_access_list_statistics_table__ipv4_loopback ON access_list_statistics_table (ipv4_loopback);
CREATE INDEX IF NOT EXISTS idx_access_list_statistics_table__device_name ON access_list_statistics_table (device_name);
CREATE INDEX IF NOT EXISTS idx_access_list_statistics_table__access_list_group ON access_list_statistics_table (access_list_group);
CREATE INDEX IF NOT EXISTS idx_access_list_statistics_table__access_list_line ON access_list_statistics_table (access_list_line);
CREATE INDEX IF NOT EXISTS idx_access_list_statistics_table__access_list_rule ON access_list_statistics_table (access_list_rule);
CREATE INDEX IF NOT EXISTS idx_access_list_statistics_table__datetimestamp ON access_list_statistics_table (datetimestamp);
CREATE INDEX IF NOT EXISTS idx_ip_arp_table__mac_address ON ip_arp_table (mac_address);
CREATE INDEX IF NOT EXISTS idx_ip_arp_table__device_name ON ip_arp_table (device_name);
CREATE INDEX IF NOT EXISTS idx_ip_arp_table__ipv4_loopback ON ip_arp_table (ipv4_loopback);
CREATE INDEX IF NOT EXISTS idx_ip_arp_table__ipv4_address ON ip_arp_table (ipv4_address);
CREATE INDEX IF NOT EXISTS idx_ip_arp_table__interface_description ON ip_arp_table (interface_description);
CREATE INDEX IF NOT EXISTS idx_ip_arp_table__datetimestamp ON ip_arp_table (datetimestamp);
CREATE INDEX IF NOT EXISTS idx_wiring_database__hub ON wiring_database (hub);
CREATE INDEX IF NOT EXISTS idx_wiring_database__port ON wiring_database (port);
CREATE INDEX IF NOT EXISTS idx_wiring_database__port_type ON wiring_database (port_type);
CREATE INDEX IF NOT EXISTS idx_wiring_database__department ON wiring_database (department);
CREATE INDEX IF NOT EXISTS idx_wiring_database__originating_building ON wiring_database (originating_building);
CREATE INDEX IF NOT EXISTS idx_wiring_database__originating_room ON wiring_database (originating_room);
CREATE INDEX IF NOT EXISTS idx_wiring_database__trunk_cable ON wiring_database (trunk_cable);
CREATE INDEX IF NOT EXISTS idx_wiring_database__trunk_pair ON wiring_database (trunk_pair);
CREATE INDEX IF NOT EXISTS idx_wiring_database__terminating_building ON wiring_database (terminating_building);
CREATE INDEX IF NOT EXISTS idx_wiring_database__station_cable ON wiring_database (station_cable);
CREATE INDEX IF NOT EXISTS idx_wiring_database__station_pair ON wiring_database (station_pair);
CREATE INDEX IF NOT EXISTS idx_wiring_database__install_order_number ON wiring_database (install_order_number);
CREATE INDEX IF NOT EXISTS idx_wiring_database__change_order ON wiring_database (change_order);
CREATE INDEX IF NOT EXISTS idx_wiring_database__technician ON wiring_database (technician);
CREATE INDEX IF NOT EXISTS idx_wiring_database__datetimestamp ON wiring_database (datetimestamp);
CREATE INDEX IF NOT EXISTS idx_wiring_database__requester ON wiring_database (requester);
CREATE INDEX IF NOT EXISTS idx_wiring_database__res_hall_service_number ON wiring_database (res_hall_service_number);
CREATE INDEX IF NOT EXISTS idx_wiring_database__res_hall_building ON wiring_database (res_hall_building);
CREATE INDEX IF NOT EXISTS idx_wiring_database__res_hall_cable_identifier ON wiring_database (res_hall_cable_identifier);
CREATE INDEX IF NOT EXISTS idx_wiring_database__res_hall_remote_location ON wiring_database (res_hall_remote_location);
CREATE INDEX IF NOT EXISTS idx_wiring_database__res_hall_nynex_cable_number ON wiring_database (res_hall_nynex_cable_number);
CREATE INDEX IF NOT EXISTS idx_wiring_database__res_hall_cable_id ON wiring_database (res_hall_cable_id);
CREATE INDEX IF NOT EXISTS idx_wiring_database__res_hall_cable_description ON wiring_database (res_hall_cable_description);
CREATE INDEX IF NOT EXISTS idx_wiring_database__res_hall_purpose ON wiring_database (res_hall_purpose);
CREATE INDEX IF NOT EXISTS idx_wiring_database__res_hall_originating_location ON wiring_database (res_hall_originating_location);
CREATE INDEX IF NOT EXISTS idx_wiring_database__res_hall_room_location ON wiring_database (res_hall_room_location);
CREATE INDEX IF NOT EXISTS idx_wiring_database__res_hall_room_location_code ON wiring_database (res_hall_room_location_code);
CREATE INDEX IF NOT EXISTS idx_wiring_database__res_hall_faceplate_position ON wiring_database (res_hall_faceplate_position);
CREATE INDEX IF NOT EXISTS idx_wiring_database__res_hall_originating_tr ON wiring_database (res_hall_originating_tr);
CREATE INDEX IF NOT EXISTS idx_wiring_database__res_hall_vlan ON wiring_database (res_hall_vlan);
CREATE INDEX IF NOT EXISTS idx_wiring_database__circuit_id_status ON wiring_database (circuit_id_status);
CREATE INDEX IF NOT EXISTS idx_wiring_database__hub_name ON wiring_database (hub_name);
CREATE INDEX IF NOT EXISTS idx_wiring_database__hub_ip ON wiring_database (hub_ip);
CREATE INDEX IF NOT EXISTS idx_discovered_device_configuration_profiles__ipv4_loopback ON discovered_device_configuration_profiles (ipv4_loopback);
CREATE INDEX IF NOT EXISTS idx_discovered_device_configuration_profiles__device_type ON discovered_device_configuration_profiles (device_type);
CREATE INDEX IF NOT EXISTS idx_discovered_device_configuration_profiles__hostname ON discovered_device_configuration_profiles (hostname);
CREATE INDEX IF NOT EXISTS idx_discovered_device_configuration_profiles__system_s_fca6e698 ON discovered_device_configuration_profiles (system_serial_number);
CREATE INDEX IF NOT EXISTS idx_discovered_device_configuration_profiles__model_number ON discovered_device_configuration_profiles (model_number);
COMMIT;