knpu_oauth2_client:
    clients:
        keycloak:
            type: generic
            provider_class: Stevenmaguire\OAuth2\Client\Provider\Keycloak
            provider_options:
                authServerUrl: '%env(KEYCLOAK_AUTH_SERVER_URL)%'   # https://auth...:8443
                realm: '%env(KEYCLOAK_REALM)%'                     # network_tools
            client_id: '%env(KEYCLOAK_CLIENT_ID)%'
            client_secret: '%env(KEYCLOAK_CLIENT_SECRET)%'
            redirect_route: connect_keycloak_check

