security:
    providers:
        keycloak_users:
            id: App\Security\KeycloakUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: keycloak_users

            custom_authenticators:
                - App\Security\KeycloakAuthenticator

            entry_point: App\Security\KeycloakAuthenticator

            logout:
                path: app_logout
                target: connect_keycloak_start
                invalidate_session: false

    access_control:
        - { path: ^/connect/keycloak, roles: PUBLIC_ACCESS }
        - { path: ^/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
